// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1vhbfTRATTO8TqvI02yqvEOwm5nHFGdI',
    appId: '1:1036948481534:web:e52022b4f3aa477ebe0caf',
    messagingSenderId: '1036948481534',
    projectId: 'finding-ally',
    authDomain: 'finding-ally.firebaseapp.com',
    storageBucket: 'finding-ally.appspot.com',
    measurementId: 'G-0PWZGP9TRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzt54DOiOOstpxLL7ps4QGwlmCE3HIn1I',
    appId: '1:1036948481534:android:5f0e163d52884073be0caf',
    messagingSenderId: '1036948481534',
    projectId: 'finding-ally',
    storageBucket: 'finding-ally.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5jPdMjj2ZPJHEFRnd0dsftA54__GRoo',
    appId: '1:1036948481534:ios:a53d8c957f95e018be0caf',
    messagingSenderId: '1036948481534',
    projectId: 'finding-ally',
    storageBucket: 'finding-ally.appspot.com',
    iosClientId: '1036948481534-h7a7r3pa9r48v6nmvthiro58svubbhlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.findingAlly',
  );
}
